export const json1 = {
  data: {
    id: 5742,
    official: 27512,
    picture: 17564,
    level: 200,
    cloth_id: 507,
    choose_effect: 0,
    give_boost: 0,
    cannot_fm: 0,
    category_id: 17,
    subcategory_id: null,
    name: 'Âmes Hurlantes',
    information: null,
    category_name: 'ca',
    category_type: 'E',
    subcategory_name: null,
    cloth_name: 'Malédiction de Cire Momore',
    swf: 3872,
    harness: null,
    main_color1: null,
    main_color2: null,
    main_color3: null,
    png_color1: null,
    png_color2: null,
    png_color3: null,
    size: null,
    cameleon: 0,
    slug: '5742-ames-hurlantes',
    effects: [
      {
        item_id: 5742,
        id: 130,
        name: 'vi',
        type: 'E',
        min: 451,
        max: 500,
        emote: null,
        title: null,
        spell: null,
        spellDesc: null,
      },
      {
        item_id: 5742,
        id: 180,
        name: 'sa',
        type: 'E',
        min: 31,
        max: 40,
        emote: null,
        title: null,
        spell: null,
        spellDesc: null,
      },
      {
        item_id: 5742,
        id: 190,
        name: 'pu',
        type: 'E',
        min: 41,
        max: 50,
        emote: null,
        title: null,
        spell: null,
        spellDesc: null,
      },
      {
        item_id: 5742,
        id: 240,
        name: 'ic',
        type: 'E',
        min: 1,
        max: 1,
        emote: null,
        title: null,
        spell: null,
        spellDesc: null,
      },
      {
        item_id: 5742,
        id: 270,
        name: 'dtf',
        type: 'E',
        min: 7,
        max: 10,
        emote: null,
        title: null,
        spell: null,
        spellDesc: null,
      },
      {
        item_id: 5742,
        id: 280,
        name: 'dff',
        type: 'E',
        min: 7,
        max: 10,
        emote: null,
        title: null,
        spell: null,
        spellDesc: null,
      },
      {
        item_id: 5742,
        id: 290,
        name: 'def',
        type: 'E',
        min: 7,
        max: 10,
        emote: null,
        title: null,
        spell: null,
        spellDesc: null,
      },
      {
        item_id: 5742,
        id: 300,
        name: 'daf',
        type: 'E',
        min: 7,
        max: 10,
        emote: null,
        title: null,
        spell: null,
        spellDesc: null,
      },
      {
        item_id: 5742,
        id: 320,
        name: 'pp',
        type: 'E',
        min: 11,
        max: 15,
        emote: null,
        title: null,
        spell: null,
        spellDesc: null,
      },
      {
        item_id: 5742,
        id: 330,
        name: 'ii',
        type: 'E',
        min: 501,
        max: 600,
        emote: null,
        title: null,
        spell: null,
        spellDesc: null,
      },
      {
        item_id: 5742,
        id: 350,
        name: 'ta',
        type: 'E',
        min: 11,
        max: 15,
        emote: null,
        title: null,
        spell: null,
        spellDesc: null,
      },
      {
        item_id: 5742,
        id: 440,
        name: 'rp',
        type: 'E',
        min: 21,
        max: 25,
        emote: null,
        title: null,
        spell: null,
        spellDesc: null,
      },
      {
        item_id: 5742,
        id: 510,
        name: 'rap',
        type: 'E',
        min: 7,
        max: 10,
        emote: null,
        title: null,
        spell: null,
        spellDesc: null,
      },
    ],
    constraints: [],
    ingredients: [
      {
        item_id: 5742,
        id: 12728,
        name: 'Ardonite',
        picture: 40710,
        count: 2,
      },
      {
        item_id: 5742,
        id: 15271,
        name: 'Tourmaline',
        picture: 50719,
        count: 15,
      },
      {
        item_id: 5742,
        id: 27402,
        name: 'Rouge à lèvres de Belladone',
        picture: 24293,
        count: 2,
      },
      {
        item_id: 5742,
        id: 27403,
        name: 'Fleur des protecteurs',
        picture: 36662,
        count: 9,
      },
      {
        item_id: 5742,
        id: 27433,
        name: 'Poils de barbe de Marteau-Aigri',
        picture: 165064,
        count: 17,
      },
      {
        item_id: 5742,
        id: 27439,
        name: 'Cloche de Barbéryl Clochecuivre',
        picture: 165063,
        count: 3,
      },
      {
        item_id: 5742,
        id: 27517,
        name: 'Cire de Cire Momore',
        picture: 165068,
        count: 3,
      },
      {
        item_id: 5742,
        id: 27518,
        name: 'Cœur de Cire Momore',
        picture: 165067,
        count: 1,
      },
    ],
    weapon: null,
  },
};
